function ready(fn){ if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', fn); } else { fn(); } }

// Helper to wait for Chart.js if script loads after DOM
function waitForChart(maxMs=3000){ return new Promise(res=>{ if(window.Chart) return res(true); const t0=performance.now(); const id=setInterval(()=>{ if(window.Chart||performance.now()-t0>maxMs){ clearInterval(id); res(!!window.Chart); } },50); }); }

document.addEventListener('DOMContentLoaded',function(){try{if(window.AOS){AOS.init({duration:800,easing:'ease-in-out',once:true,offset:100});}}catch(_){} const e=document.querySelector('.perf-grid');if(e){const t=new IntersectionObserver(n=>{n.forEach(o=>{if(o.isIntersecting){if('true'!==e.getAttribute('data-locked')){const r=e.querySelectorAll('.perf-number');r&&r.length&&animateStats(r)}t.unobserve(e)}})},{threshold:.4});t.observe(e)}});function animateStats(nodes){
  const easeOutCubic=t=>1-Math.pow(1-t,3);
  const formatMoney=v=>{const parts=v.toFixed(1).split('.');parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');return parts.join('.')};
  nodes.forEach(node=>{const originalText=node.textContent||'';let target=0,prefix='',suffix='';if(originalText.includes('$')){prefix='$';target=parseFloat(originalText.replace(/[^\d.]/g,''));}else if(originalText.includes('%')){suffix='%';target=parseFloat(originalText.replace(/[^\d.]/g,''));}else if(originalText.includes('+')){suffix='+';target=parseFloat(originalText.replace(/[^\d.]/g,''));}else{target=parseFloat(originalText.replace(/[^\d.]/g,''));}const durationMs=1200;let startTs=null;function step(ts){if(startTs===null) startTs=ts;const t=Math.min((ts-startTs)/durationMs,1);const value=target*easeOutCubic(t);if(prefix==='$') node.textContent=prefix+formatMoney(value); else if(suffix==='%'||suffix==='+') node.textContent=Math.round(value)+suffix; else node.textContent=Math.round(value).toString(); if(t<1) requestAnimationFrame(step); else node.textContent=originalText;}requestAnimationFrame(step);});}

// Enhance trades table: search + sort control + aria-live announcements
(function(){
  const CSV_URL = 'assets/data/SPY-SMA20-Trades-static.csv';
  const TABLE_ID = 'trades-table';
  const SEARCH_ID = 'trades-search';
  const FILTER_ID = 'trades-action-filter';
  const SORT_ID = 'trades-sort';
  const ARIA_ID = 'trades-aria';
  const PAGE_SIZE = 25;
  let allRows = [], filteredRows = [], sortCol = 'Date', sortDir = 'asc', page = 1;

  function announce(msg){ const n=document.getElementById(ARIA_ID); if(n){ n.textContent = msg; } }
  function parseCSV(text){ const lines=text.trim().split(/\r?\n/); if(!lines.length) return []; const headers=lines[0].split(',').map(h=>h.replace(/^\ufeff/, '').trim()); return lines.slice(1).map(line=>{ const vals=[],re=/(?:"([^"]*)")|([^,]+)/g; let m; while((m=re.exec(line))!==null) vals.push((m[1]||m[2]||'').trim()); while(vals.length<headers.length) vals.push(''); const obj={}; headers.forEach((h,j)=>obj[h]=vals[j]||''); return obj; }); }
  function formatMoney(v){ const n=Number(v)||0; return n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}); }
  function renderTable(){ const tableDiv=document.getElementById(TABLE_ID); if(!tableDiv) return; if(!filteredRows.length){ tableDiv.innerHTML = '<table class="trades-table"><thead><tr>'+['Date','Action','Price','Shares','Capital After','Trade Profit','Portfolio Value'].map(h=>`<th scope="col">${h}</th>`).join('')+'</tr></thead><tbody><tr class="empty-row"><td colspan="7">No trades found.</td></tr></tbody></table>'; return; } const start=(page-1)*PAGE_SIZE,end=start+PAGE_SIZE; const pageRows=filteredRows.slice(start,end); const ths=['Date','Action','Price','Shares','Capital After','Trade Profit','Portfolio Value'].map(h=>{ let cls='sortable'; if(sortCol===h) cls+=' sorted-'+sortDir; return `<th scope="col" class="${cls}" data-col="${h}">${h}</th>`; }).join(''); const moneyCols={'Price':true,'Capital After':true,'Trade Profit':true,'Portfolio Value':true}; const trs=pageRows.map(r=>{ const tds=['Date','Action','Price','Shares','Capital After','Trade Profit','Portfolio Value'].map(k=>{ const v=r[k]||''; if(moneyCols[k] && v!==''){ const n=parseFloat(v)||0; return `<td class="num-cell" data-num="${n}" data-fmt="money">${formatMoney(n)}</td>`; } return `<td>${v}</td>`; }).join(''); const cls=(r.Action||'').toUpperCase()==='SELL'?' style="border-left:2px solid #e6e6e6"':''; return `<tr${cls}>${tds}</tr>`; }).join(''); tableDiv.innerHTML = `<table class="trades-table"><thead><tr>${ths}</tr></thead><tbody>${trs}</tbody></table>`+`<div class="trades-pagination"><button class="trades-btn" ${page===1?'disabled':''}>Prev</button><span class="page-info">Page ${page} of ${Math.ceil(filteredRows.length/PAGE_SIZE)}</span><button class="trades-btn" ${end>=filteredRows.length?'disabled':''}>Next</button></div>`; tableDiv.querySelectorAll('th.sortable').forEach(th=>{ th.onclick=()=>{ const col=th.getAttribute('data-col'); if(sortCol===col) sortDir=sortDir==='asc'?'desc':'asc'; else {sortCol=col; sortDir='asc';} sortRows(); page=1; renderTable(); announce(`Sorted by ${sortCol} ${sortDir}`); }; }); const btns=tableDiv.querySelectorAll('.trades-pagination button'); const prev=btns[0], next=btns[1]; if(prev) prev.onclick=()=>{ if(page>1){ page--; renderTable(); announce(`Page ${page}`);} }; if(next) next.onclick=()=>{ const maxPage=Math.ceil(filteredRows.length/PAGE_SIZE); if(page<maxPage){ page++; renderTable(); announce(`Page ${page}`);} }; }
  function sortRows(){ filteredRows.sort((a,b)=>{ let v1=a[sortCol],v2=b[sortCol]; if(sortCol==='Date'){ v1=v1||''; v2=v2||''; return sortDir==='asc'?v1.localeCompare(v2):v2.localeCompare(v1); } if(['Price','Shares','Capital After','Trade Profit','Portfolio Value'].includes(sortCol)){ v1=parseFloat(v1)||0; v2=parseFloat(v2)||0; return sortDir==='asc'?v1-v2:v2-v1; } return sortDir==='asc'?(v1||'').localeCompare(v2||''):(v2||'').localeCompare(v1||''); }); }
  function applyFilters(){ const q=(document.getElementById(SEARCH_ID)?.value||'').toLowerCase(); const act=document.getElementById(FILTER_ID)?.value||''; const sortSel=document.getElementById(SORT_ID)?.value||'oldest'; sortCol='Date'; sortDir= sortSel==='oldest' ? 'asc':'desc'; filteredRows = allRows.filter(r=>{ if(act && (r.Action||'')!==act) return false; if(!q) return true; return Object.values(r).some(v=> (v||'').toString().toLowerCase().includes(q)); }); sortRows(); page=1; renderTable(); announce(`Filter ${act||'All'}, ${filteredRows.length} rows`); }
  let t; function debounce(){ clearTimeout(t); t=setTimeout(applyFilters,200); }
  async function init(){ try{ console.debug('[Trades] Fetch', CSV_URL); const res=await fetch(CSV_URL,{cache:'no-cache'}); if(!res.ok) throw 0; const text=await res.text(); allRows = parseCSV(text); allRows.sort((a,b)=> (a.Date||'').localeCompare(b.Date||'')); filteredRows = allRows.slice(); sortCol='Date'; sortDir='asc'; page=1; renderTable(); const s=document.getElementById(SEARCH_ID), f=document.getElementById(FILTER_ID), so=document.getElementById(SORT_ID); s&&s.addEventListener('input',debounce); f&&f.addEventListener('change',applyFilters); so&&so.addEventListener('change',applyFilters); }catch(e){ const tableDiv=document.getElementById(TABLE_ID); if(tableDiv) tableDiv.innerHTML = `<div class="trades-table-fallback">Unable to load trade log. <a href="${CSV_URL}" download>Download CSV</a></div>`; console.error('[Trades] Load failed', e);} }
  if(document.getElementById(TABLE_ID)) ready(init);
})();

// Animate performance card numbers when visible
(function(){
  const prefersReduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const ease = t=>1-Math.pow(1-t,3);
  const formatNumber = (n, d=0) => { const parts=Number(n||0).toFixed(d).split('.'); parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,','); return parts.join(d?'.':''); };
  function runAnimation(){ if(prefersReduced) return; const grid=document.querySelector('.perf-grid'); if(!grid||grid.dataset.animated==='true') return; const nums=grid.querySelectorAll('.perf-number'); nums.forEach(node=>{ const original=node.textContent||''; let target=0,type='int',hasK=false; if(original.includes('$')){ type='money'; hasK=/k/i.test(original); target=parseFloat(original.replace(/[^\d.\-]/g,''))||0; } else if(original.includes('%')){ type='percent'; target=parseFloat(original.replace(/[^\d.\-]/g,''))||0; } else if(original.includes('+')){ type='plus'; target=parseFloat(original.replace(/[^\d.\-]/g,''))||0; } else { type='int'; target=parseFloat(original.replace(/[^\d.\-]/g,''))||0; } const dur=1100; let startTs=null; function step(ts){ if(startTs===null) startTs=ts; const t=Math.min((ts-startTs)/dur,1); const val=target*ease(t); if(type==='money'){ node.textContent = hasK? `$${formatNumber(val,1)}K` : `$${formatNumber(val,2)}`; } else if(type==='percent'){ node.textContent = `${Math.round(val)}%`; } else if(type==='plus'){ node.textContent = `${Math.round(val)}+`; } else { node.textContent = `${Math.round(val)}`; } if(t<1) requestAnimationFrame(step); else node.textContent=original; } requestAnimationFrame(step); }); grid.dataset.animated='true'; }
  function init(){ const grid=document.querySelector('.perf-grid'); if(!grid) return; const obs=new IntersectionObserver((entries)=>{ entries.forEach(e=>{ if(e.isIntersecting){ runAnimation(); obs.disconnect(); } }); },{threshold:.45}); obs.observe(grid); }
  ready(init);
})();

// Equity chart and badge percent update
(function(){
  const prefersReduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const EQUITY_CSV = 'assets/data/SPY-SMA20-Equity-static.csv';
  const currencyFormat = (n) => { const v=Number(n||0); const parts=v.toFixed(2).split('.'); parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ','); return `$${parts.join('.')}`; };
  function parseCSV(text){ const lines=text.trim().split(/\r?\n/); if(!lines.length) return []; const headers=lines[0].split(',').map(h=>h.replace(/^\ufeff/, '').trim()); return lines.slice(1).map(line=>{ const vals=[],re=/(?:"([^"]*)")|([^,]+)/g; let m; while((m=re.exec(line))!==null) vals.push((m[1]||m[2]||'').trim()); while(vals.length<headers.length) vals.push(''); const o={}; headers.forEach((h,j)=>o[h]=vals[j]||''); return o; }); }
  function sortAsc(rows){ return rows.sort((a,b)=>String(a.Date||'').localeCompare(String(b.Date||''))); }
  async function init(){ try{ console.debug('[Equity] Fetch', EQUITY_CSV); const res=await fetch(EQUITY_CSV,{cache:'no-cache'}); if(!res.ok) throw 0; const text=await res.text(); const rows=sortAsc(parseCSV(text)); if(!rows.length) { const fb=document.getElementById('equity-fallback'); if(fb) fb.hidden=false; return; } const series=rows.map(r=>({d:r.Date,v:parseFloat(String(r['Portfolio Value']||'').replace(/[^\d.\-]/g,''))||0})); const start=series[0].v, end=series[series.length-1].v; const ret=start? ((end-start)/start*100):0; const badge=document.getElementById('perf-badge'); if(badge){ badge.textContent=(ret>=0?'+':'')+ret.toFixed(2)+'%'; badge.classList.toggle('positive',ret>=0); badge.classList.toggle('negative',ret<0); } const ctx=document.getElementById('equityChart'); if(!ctx) return; const hasChart = await waitForChart(); if(!hasChart) return; Chart.defaults.font.family="Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"; const labels=series.map(p=>p.d); const data=series.map(p=>p.v); const animation = prefersReduced? false : { duration:1200, easing:'easeOutExpo' }; new Chart(ctx, {type:'line', data:{ labels, datasets:[{ label:'Portfolio Value', data, borderColor:'#111', borderWidth:1.5, tension:.25, pointRadius:0 }] }, options:{ responsive:true, animation, plugins:{ legend:{display:false}, tooltip:{mode:'index',intersect:false,callbacks:{ label:(c)=>` ${currencyFormat(c.parsed.y)}` } } }, scales:{ x:{ display:true, ticks:{ maxTicksLimit:6 } }, y:{ display:true, ticks:{ callback:(v)=>'$'+Number(v).toLocaleString() } } } }}); } catch(e){ const fb=document.getElementById('equity-fallback'); if(fb) fb.hidden=false; console.error('[Equity] Load failed', e); } }
  ready(init);
})();

function prefersReducedMotion(){ return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches; }
function observeOnce(el, cb){ const io=new IntersectionObserver((es,o)=>{es.forEach(e=>{if(e.isIntersecting){cb(e.target);o.unobserve(e.target);}})},{threshold:.3}); io.observe(el); }
function initScrambleOnView(selector){ if(prefersReducedMotion()) return; const rng='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'; document.querySelectorAll(selector).forEach(el=>{ const final=el.getAttribute('data-final')||el.textContent; observeOnce(el,()=>{ const dur=700,t0=performance.now(); (function tick(t){ const p=Math.min((t-t0)/dur,1); el.textContent=[...final].map(ch=>ch===' ' ? ' ' : (Math.random()<(1-p)? rng[(Math.random()*rng.length)|0] : ch)).join(''); if(p<1) requestAnimationFrame(tick); else el.textContent=final; })(t0); }); }); }
ready(()=>initScrambleOnView('.future-roadmap .title.scramble'));

/* Slot-machine reveal disabled (reverted to original count-up) */
function slotRevealNumbers(){}
ready(slotRevealNumbers);


